version: '3'
services:
  mongo:
    image: 'mongo:5.0.3'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=verysecret
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: 'mongo-express:latest'
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=verysecret
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=verysecret
    depends_on:
      - mongo
    ports:
      - "8888:8081"
  # score-tracker-server:
  #   build: Dockerfile
  #   image: eatici/osu-top-scores:latest
  #   restart: always
  #   environment:
  #     MONGODB_URL=mongodb://host.docker.internal
  #     OSU_CLIENT_ID=/run/secrets/osu_client_id
  #     OSU_CLIENT_SECRET=/run/secrets/osu_client_secret
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.fastapi.rule=Host(`top500.ronnia.me`)"
  #     - "traefik.http.routers.fastapi.tls=true"
  #     - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
  #   expose:
  #     - 8000
  # score-tracker-user-update:
  #   build: user-update-cron/Dockerfile
  #   environment:
  #     - MONGODB_URL=mongodb://host.docker.internal
  # traefik:
  #   image: traefik:v2.2
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /home/efehanatici/traefik/traefik.prod.toml:/etc/traefik/traefik.toml

