version: '3'
services:
  mongo:
    image: 'mongo:5.0.3'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=verysecret
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
